import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <h1>Layout default</h1>
      <body className={inter.className}>
        <Link href="/">Anasayfa</Link> <br/>
        <Link href="/about">About</Link><br/>
        <Link href="/blog/65465">Blog</Link>
        {children}
        </body>
    </html>
  );
}
