import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css'
// import { ErrorBoundary } from "next/dist/client/components/error-boundary";
// import Error from "./error";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-dark">
        <Navbar />
        {/* <ErrorBoundary fallback={<Error />}> */}
          {children}
        {/* </ErrorBoundary> */}
      </body>
    </html>
  );
}
