import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
<<<<<<< Updated upstream
import Navbar from "../components/Navbar";
=======
>>>>>>> Stashed changes

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
<<<<<<< Updated upstream
        <Navbar />
=======
        <Link href="/">Home</Link>
        <Link href="/blog">Denemeblog</Link>
>>>>>>> Stashed changes
        {children}
      </body>
    </html>
  );
}
