export const data = [
  {
    gif: "assets/bookify.gif",
    name: "Bookify",
    techs: ["sass", "bootstrap", "js"],
    desc: "With the Bookify project, you can create your own library, use it as a wishlist or keep track of the books you read. In this project, I used Bootstrap and SCSS in the UI to create a modern design. I used JSON-Server to save the data and performed all frontend operations with Vanilla JavaScript.",
  },
  {
    gif: "assets/flight.gif",
    name: "FlyPqs",
    techs: ["tailwind", "react"],
    desc: "FlyPqs is a dynamic web application that enables users to search and list flights on specific dates and at airports. It stands out with its intuitive interface and visual animation presented at first use. Flight information is showcased with easy sorting and filtering features, prioritizing user experience.",
  },
  {
    gif: "assets/movie.gif",
    name: "Watchlyst",
    techs: ["tailwind", "react", "redux"],
    desc: "Watchlyst, using the TMDB API, is a React-based platform allowing users to easily create and manage personalized watchlists. Discover the latest and popular movies, search for specific titles, and access detailed information on individual movie pages. Tailwind CSS ensures a sleek design. After watching, effortlessly remove movies from your watchlist. Streamlining movie discovery and user control, Watchlyst offers a concise and user-friendly experience.",
  },
  {
    gif: "assets/xox.gif",
    name: "Tic-Tac-Toe",
    techs: ["css", "js"],
    desc: "Tic-Tac-Toe is a classic game implemented using simple HTML, CSS, and JavaScript. It features a minimalist design and intuitive user interface, making it easy and fun to play. The game allows two players to compete against each other.",
  },
  {
    gif: "assets/wormhole.gif",
    name: "Wormhole",
    techs: ["css", "sass", "bootstrap"],
    desc: "The Wormhole project represents an e-commerce site that allows renting time machines. In this project, my goal was to design a user interface suitable for the theme using Bootstrap and SASS/SCSS.",
  },
  {
    gif: "assets/rock.gif",
    name: "Rock-Paper-Scissors",
    techs: ["css", "js"],
    desc: "Rock-Paper-Scissors is a simple and fun game built with HTML, CSS, and JavaScript. Players can compete against the computer, which uses random choices to play. The interface is designed to be engaging and visually appealing, making it an enjoyable quick game.",
  },
  {
    gif: "assets/memory.gif",
    name: "Memory Game",
    techs: ["css", "js"],
    desc: "Memory Game is an interactive and educational game designed to test and improve memory skills. Built with HTML, CSS, and JavaScript. Players flip cards to find matching pairs, aiming to complete the game in the fewest moves possible.",
  },
  {
    gif: "assets/dvh.gif",
    name: "Digital Vehicle License",
    techs: ["solidity", "tailwind", "react"],
    desc: "Digital Vehicle Licence is a project that aims to revolutionise the way vehicle records are managed and accessed. Using blockchain technology, it enables secure, transparent and immutable record keeping. Features include accident records, maintenance and inspection records, historical ownership information, and tracking the condition of vehicle parts.",
  },
  {
    gif: "assets/skyhub.gif",
    name: "SkyHub",
    techs: ["tailwind", "react", "redux"],
    desc: "In this project, a user-friendly website has been prepared that allows users to seamlessly view location information as well as the current weather page. The search page allows effortless checking of the weather for any desired location. More importantly, cities can be added to favourites, making it easier to track weather information for preferred locations.",
  },
  //   {
  //     gif: "assets/skyhub.gif",
  //     name: "Cover Letter Generator",
  //     techs: ["tailwind", "react"],
  //     desc: "This project aims to develop a software application that offers users the opportunity to create cover letters quickly and effectively. After entering their personal information and details about the position they are applying for, users will have a professionally prepared cover letter generated by artificial intelligence.",
  //   },
  {
    gif: "assets/2000words.gif",
    name: "2000Words",
    techs: ["tailwind", "react", "nodejs", "mongodb", "expressjs"],
    desc: "2000Words is a practical and interactive educational platform for learning the basic 2000 words in the English language. Users can easily learn and practice unfamiliar words with smart flash cards. Enrich your language skills and make your communication more effective with the power of 2000 words.",
  },
];
