import Header from "@/components/Header";
import "../css/main.css"
import Cto from "@/components/Cto";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Cto/>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
