import "bootstrap/dist/css/bootstrap.min.css";

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/navbar";
import Footer from "../components/Footer/footer";
import Container from "../components/Container/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Final",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Container> {children} </Container>
        <Footer />
      </body>
    </html>
  );
}
