import "./css/main.css"
import { Providers } from "./redux/provider"
import { Toaster } from 'react-hot-toast'

export const metadata = {
  title: "ShopCo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}