import { Inter } from "next/font/google";
import "./globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div className="offer text-center bg-black text-white">
            <p className="py-2">
              Sign up and get 20% off to your first order.&nbsp;
              <a className="fw-medium link-light" href="#">
                Sign Up Now
              </a>
            </p>
          </div>
          <div className="container d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start py-4">
            <a
              className="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none"
              href="#"
            >
              <Image src="/SHOP.CO.png" width="160" height="22" />
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li>
                <a
                  class="dropdown-toggle nav-link px-2 text-black"
                  href="#"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Shop
                </a>
              </li>
              <li>
                <a href="#" class="nav-link px-2 text-black">
                  On Sale
                </a>
              </li>
              <li>
                <a href="#" class="nav-link px-2 text-black">
                  New Arrivals
                </a>
              </li>
              <li>
                <a href="#" class="nav-link px-2 text-black">
                  Brands
                </a>
              </li>
            </ul>
            <form
              class="search-form col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3"
              role="search"
            >
              <input
                type="search"
                class="form-control"
                placeholder="Search for products..."
                aria-label="Search"
              />
            </form>
            <div className="nav-icons">
              <Image src="/Frame.png" width="24" height="24" />
              <Image src="/Vector.png" width="24" height="24" />
            </div>
          </div>
        </nav>
        {children}
        <footer>
          <div className="container">
            <div className="subscribe-box bg-black d-flex justify-content-between align-items-center flex-wrap">
              <h1 className="fw-bold text-white">
                STAY UPTO DATE ABOUT
                <br />
                OUR LATEST OFFERS
              </h1>
              <div className="subscribe-form d-flex flex-column">
                <input
                  type="subscribe"
                  placeholder="Enter your email address"
                  aria-label="Subscribe"
                />
                <button className="fw-medium">Subscribe to Newsletter</button>
              </div>
            </div>
            <div className="footer-box d-flex justify-content-between flex-wrap">
              <div className="box1 d-flex flex-column">
                <a href="#">
                  <Image src="/SHOP.CO.png" width="167" height="23" />
                </a>
                <p>
                  We have clothes that suits your style and
                  <br />
                  which you’re proud to wear. From
                  <br />
                  women to men.
                </p>
                <div className="d-flex gap-3">
                  <a href="#">
                    <Image src="/twitter.png" width="28" height="28" />
                  </a>
                  <a className="bg-black" href="#">
                    <Image src="/facebook.png" width="28" height="28" />
                  </a>
                  <a href="#">
                    <Image src="/instagram.png" width="28" height="28" />
                  </a>
                  <a href="#">
                    <Image src="/github.png" width="28" height="28" />
                  </a>
                </div>
              </div>
              <div className="box2">
                <ul className="nav d-flex flex-column align-items-start">
                  <li className="heading nav-link text-black fw-medium">
                    COMPANY
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      About
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      Features
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      Works
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      Career
                    </a>
                  </li>
                </ul>
              </div>
              <div className="box3">
                <ul className="nav d-flex flex-column align-items-start">
                  <li className="heading nav-link text-black fw-medium">
                    HELP
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      Customer Support
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      Delivery Details
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      Terms & Conditions
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      Privacy Policy
                    </a>
                  </li>
                </ul>
              </div>
              <div className="box4">
                <ul className="nav d-flex flex-column align-items-start">
                  <li className="heading nav-link text-black fw-medium">FAQ</li>
                  <li>
                    <a href="#" class="nav-link">
                      Account
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      Manage Deliveries
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      Orders
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      Payments
                    </a>
                  </li>
                </ul>
              </div>
              <div className="box5">
                <ul className="nav d-flex flex-column align-items-start">
                  <li className="heading nav-link text-black fw-medium">
                    RESOURCES
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      Free eBooks
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      Development Tutorial
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      How to - Blog
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link">
                      Youtube Playlist
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div className="all-rights d-flex justify-content-between align-items-baseline flex-wrap">
              <p>Shop.co © 2000-2023, All Rights Reserved</p>
              <div>
                <Image src="/visa.png" width="47" height="30" />
                <Image src="/mastercard.png" width="47" height="30" />
                <Image src="/paypal.png" width="47" height="30" />
                <Image src="/applepay.png" width="47" height="30" />
                <Image src="/googlepay.png" width="47" height="30" />
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
