import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Link href="/">Anasayfa</Link>
      <Link href="/about">Hakkında</Link>
      <Link href="/blog/08">Blog</Link>
      Bu Genel Layout
      <body className={inter.className}>{children}</body>
    </html>
  );
}
