import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/">Ana Sayfaya git</Link><br />
        <Link href="/about">Abouta git</Link><br />
        <Link href="/deneme/deneme-1">Denemeye git</Link><br />
        <Link href="/blog/blog-1">Bloga git</Link><br /><br />
        <h1> - Bu Genel Layout - </h1><br />
        {children}
      </body>
    </html>
  );
}
